title: Dominik Waldburger
description: >
  Informatiker EFZ Applikationsentwicklung mit Fokus auf Softwareentwicklung,
  technische Analyse, Schnittstellen, Automatisierung und praxisnahe IT-Themen.

theme: jekyll-theme-minimal

show_downloads: false

github:
  is_project_page: false
